repo_path: "/home/fjammes/src/github.com/astrolabsoftware/fink-broker"
check_interval: 5m
test_script: "./e2e/fink-ci.sh"
options: "-c -i ztf"
max_commit_age: 240h

cleanup:
  after_e2e: true
  script:

github_actions_dispatch:
  enabled: true
  github_repo: "astrolabsoftware/fink-broker"