repo_path: "/tmp/test-repo-timeout"
check_interval: 10s
test_script: "_e2e/run-slow-test.sh"
options: ""
max_commit_age: 240h
test_timeout: 30s  # Short timeout to test timeout behavior
fetch_remote: false
max_concurrent_runs: 1

cleanup:
  after_e2e: false
  script: ""

github_actions_dispatch:
  enabled: false
  github_repo: ""