repo_path: "/tmp/test-repo-home-ci"
check_interval: 30s
test_script: "_e2e/run-e2e.sh"
options: "-c -i ztf"
max_commit_age: 240h
test_timeout: 10m
fetch_remote: false
max_concurrent_runs: 1

cleanup:
  after_e2e: false
  script: ""

github_actions_dispatch:
  enabled: false
  github_repo: ""