repo_path: "/tmp/home-ci/e2e/normal/repo"
check_interval: 30s
test_script: "e2e/run-e2e.sh"
options: "-c -i ztf"
max_commit_age: 240h
test_timeout: 10m
fetch_remote: false
max_concurrent_runs: 1
keep_time: 24h  # Preserve test data for debugging

cleanup:
  after_e2e: false
  script: ""

github_actions_dispatch:
  enabled: false
  github_repo: ""