name: E2E Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      home-ci-artifact: ${{ steps.upload-home-ci.outputs.artifact-id }}
      e2e-artifact: ${{ steps.upload-e2e.outputs.artifact-id }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build home-ci
      run: make build

    - name: Build e2e test harness
      run: make build-e2e

    - name: Upload home-ci binary
      id: upload-home-ci
      uses: actions/upload-artifact@v4
      with:
        name: home-ci-binary
        path: home-ci
        retention-days: 1

    - name: Upload e2e test harness
      id: upload-e2e
      uses: actions/upload-artifact@v4
      with:
        name: e2e-home-ci-binary
        path: e2e-home-ci
        retention-days: 1

  test-quick:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download home-ci binary
      uses: actions/download-artifact@v4
      with:
        name: home-ci-binary

    - name: Download e2e test harness
      uses: actions/download-artifact@v4
      with:
        name: e2e-home-ci-binary

    - name: Make binaries executable
      run: |
        chmod +x home-ci
        chmod +x e2e-home-ci

    - name: Run quick tests
      run: ./e2e-home-ci -type=quick -duration=30s

  test-normal:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download home-ci binary
      uses: actions/download-artifact@v4
      with:
        name: home-ci-binary

    - name: Download e2e test harness
      uses: actions/download-artifact@v4
      with:
        name: e2e-home-ci-binary

    - name: Make binaries executable
      run: |
        chmod +x home-ci
        chmod +x e2e-home-ci

    - name: Run normal tests
      run: ./e2e-home-ci -type=normal -duration=3m

  test-timeout:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download home-ci binary
      uses: actions/download-artifact@v4
      with:
        name: home-ci-binary

    - name: Download e2e test harness
      uses: actions/download-artifact@v4
      with:
        name: e2e-home-ci-binary

    - name: Make binaries executable
      run: |
        chmod +x home-ci
        chmod +x e2e-home-ci

    - name: Run timeout tests
      run: ./e2e-home-ci -type=timeout